[package]
name = "api-server-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["typed-header"] }
axum-macros = "0.5.1"
axum-valid = "0.24.0"
constant_time_eq = "0.4.2"
dotenvy = "0.15.7"
jsonwebtoken = "10.4.0"
phonenumber = "0.3.9"
regex = "1.12.4"
sea-query = { version = "1.0.1", features = ["with-json"] }
sea-query-sqlx = { version = "0.9.1", features = ["sqlx-postgres", "with-json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sqlx = { version = "0.9.0", features = ["json", "migrate", "postgres", "runtime-tokio", "time"] }
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.18"
time = { version = "0.3.51", features = ["serde", "formatting"] } 
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.7.0", features = ["cors", "trace"] }
validator = { version = "0.20.0", features = ["derive"] }
